"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        from functools import reduce
        return chr(reduce(lambda x, y: x ^ y, [ord(i) for i in s + t]))

if __name__ == "__main__":
    s = 'hello'
    t = 'hlelow'
    print(Solution().findTheDifference(s, t))
    
